spring.application.name=Online_Voting_System

spring.datasource.url=jdbc:mysql://localhost:3306/online_voting
spring.datasource.username=root
spring.datasource.password=A@rsha13

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true